import pyautogui
import os
from pathlib import Path

#Base paths
BASE_DIR = Path(__file__).resolve().parent.parent
MEMORY_PATH = BASE_DIR / "memory.db"
LOG_PATH = BASE_DIR / "logs"
LOG_PATH.mkdir(exist_ok=True)

#Models
PLANNER_MODEL="gemini-2.5-flash"
VISION_MODEL="gemini-2.5-flash"

#Response limits
MAX_PLAN_TOKENS = 2000
MAX_VISION_TOKENS = 2000


#Timeouts
APP_OPEN_TIMEOUT = 5 # was 10 — Notepad opens in <2s
ELEMENT_TIMEOUT = 3  # was 5
PAGE_LOAD_TIMEOUT = 15
VERIFICATION_TIMEOUT = 3
ACTION_COOLDOWN = 0.3 # was 0.5 — saves 0.2s per action

#Retry
MAX_RETRIES_PER_STEP=2
MAX_TOTAL_STEPS=25

#OCR
TESSERACT_PATH         = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
OCR_CONFIDENCE_MIN     = 60     # discard words below this confidence (0-100)
OCR_LANGUAGE           = "eng"
OCR_SCREENSHOT_WIDTH   = 1280   # downscale before OCR for speed


# ---------------------------------------------------------------------------
# Phase 3 — CDP Browser Attach
# ---------------------------------------------------------------------------
#
# BROWSER_MODE controls whether the agent spins up its own managed browser
# or attaches to your already-running Chrome via the Chrome DevTools Protocol.
#
#   "launch"  (default) — Playwright launches a fresh Chromium instance for
#             every task. No real cookies/sessions. Safe sandbox. This is the
#             existing behavior up through Phase 2.5d.
#
#   "attach"  — Playwright connects to an already-running Chrome (or any
#             Chromium-based browser) over CDP at CDP_URL. Your real
#             cookies, sessions, and logged-in state are available.
#             Cleanup: close() only disconnects Playwright; it never kills
#             your real browser process.
#
# To use attach mode:
#   1. Start Chrome with the debug port open (see scripts/launch_chrome_cdp.bat
#      or scripts/launch_chrome_cdp.sh — generated by this phase).
#   2. Set BROWSER_MODE=attach in your .env  (or export it in your shell).
#   3. Run the agent normally.  It will automatically use your live session.
#
# CDP_URL defaults to http://localhost:9222 which matches Chrome's default
# --remote-debugging-port. Override in .env if you use a different port.
#
BROWSER_MODE: str = os.getenv("BROWSER_MODE", "launch")   # "launch" | "attach"
CDP_URL:      str = os.getenv("CDP_URL",      "http://localhost:9222")

# How long (ms) to wait for an existing tab to be found / page to settle
# when attaching to a running browser. Only used in attach mode.
CDP_ATTACH_TIMEOUT_MS: int = int(os.getenv("CDP_ATTACH_TIMEOUT_MS", "10000"))

# In attach mode, should we reuse the currently-active tab or always open
# a new one?  "reuse" keeps your browsing session intact; "new" is cleaner
# for automation but opens a tab the user will see afterwards.
CDP_TAB_POLICY: str = os.getenv("CDP_TAB_POLICY", "new")  # "new" | "reuse"


#Browser (launch-mode settings — ignored in attach mode)
BROWSER_TYPE = "chromium"  # Options: "chromium", "firefox", "webkit"
HEADLESS = False # Set to True = no visible window
DEFAULT_TIMEOUT = 30_000  # in milliseconds

#Memory Settings
MEMORY_DB_PATH = str(MEMORY_PATH)
SIMILAR_TASK_THRESHOLD = 0.70
MAX_MEMORY_HINTS = 3
FAILURE_THRESHOLD = 2

# ---------------------------------------------------------------------------
# Phase 5 — Vector Memory
# ---------------------------------------------------------------------------
#
# MEMORY_SIMILARITY_BACKEND controls how memory.py compares task descriptions
# for "find similar past task" lookups.
#
#   "embedding" (default) — Use Gemini's embed_content endpoint. Two tasks
#             phrased completely differently ("grab today's headlines" vs
#             "check the news") but semantically the same will now match.
#             Falls back to "sequence" automatically, per-call, if the
#             embedding API is unreachable (no key, no network, rate limit).
#
#   "sequence" — The original Phase 1-4 behavior: difflib.SequenceMatcher
#             string-similarity only. No network calls. Useful if you want
#             fully offline memory or want to disable embedding spend.
#
MEMORY_SIMILARITY_BACKEND: str = os.getenv("MEMORY_SIMILARITY_BACKEND", "embedding")

# gemini-embedding-001 supports Matryoshka truncation down to smaller
# dimensions with minimal quality loss (per Google's MRL training) — 768
# keeps each stored vector small (~3KB as JSON) while still comfortably
# beating SequenceMatcher on semantic matches. Bump toward 1536/3072 if
# you have a large memory.db and want higher recall.
EMBEDDING_MODEL: str = os.getenv("EMBEDDING_MODEL", "gemini-embedding-001")
EMBEDDING_DIMENSIONALITY: int = int(os.getenv("EMBEDDING_DIMENSIONALITY", "768"))

# Cosine similarity threshold for the embedding backend. NOT the same scale
# as SIMILAR_TASK_THRESHOLD (SequenceMatcher ratio) — cosine similarity
# between two related-but-differently-worded sentences typically lands
# ~0.55-0.75, whereas SequenceMatcher needs near-identical wording to hit
# 0.70. Tune independently.
EMBEDDING_SIMILARITY_THRESHOLD: float = float(
    os.getenv("EMBEDDING_SIMILARITY_THRESHOLD", "0.55")
)

# Screenshot (vision fallback only)
SCREENSHOT_WIDTH = 1280

# ---------------------------------------------------------------------------
# Phase 6 — Multi-agent Supervisor
# ---------------------------------------------------------------------------
#
# ENABLE_MULTI_AGENT_SUPERVISOR: when True, every incoming task is first
# checked by Brain.decompose_task() for genuinely independent subtasks
# ("check the weather in NYC and also look up AAPL's stock price" — neither
# needs the other's output) that can run at the same time. When False, or
# when decomposition finds nothing splittable, every task goes straight to
# the normal single-agent plan -> execute -> verify loop exactly as it did
# before Phase 6 existed. This is strictly additive: worst case (decompose
# call fails, or finds no parallel split, or the split isn't tool-safe — see
# PARALLEL_SAFE_TOOLS below) is identical to pre-Phase-6 behavior.
ENABLE_MULTI_AGENT_SUPERVISOR: bool = (
    os.getenv("ENABLE_MULTI_AGENT_SUPERVISOR", "true").lower() == "true"
)

# Hard cap on how many subtasks run concurrently, even if Brain decomposes
# a task into more pieces than this. Keeps one task from launching an
# unbounded number of Chromium instances.
MAX_PARALLEL_SUBTASKS: int = int(os.getenv("MAX_PARALLEL_SUBTASKS", "3"))

# Tools considered safe to run inside a parallel worker thread.
#
# BROWSER is safe because BrowserTools drives pages via Playwright's CDP
# protocol (page.click, page.fill, ...) — synthetic events dispatched
# straight to the browser process, NOT real OS mouse/keyboard input. Each
# worker gets its own Playwright browser instance (see graph.py's
# thread-local _browser_local), so N workers can each drive their own
# Chromium window at once without fighting over anything.
#
# FILES is safe for the same reason distinct file handles are safe in any
# multithreaded program: independent subtasks (enforced by
# Brain.decompose_task's independence check) essentially never touch the
# same path at the same moment.
#
# WINDOWS_UI, APPS, OCR, and VISION are deliberately EXCLUDED. They drive
# the one real mouse/keyboard or read the one real screen — there is
# exactly one of each on this machine, so two threads clicking or
# screenshotting at once is not a performance question, it's just broken.
# If ANY subtask in a decomposition needs one of those tools, the
# supervisor abandons the parallel path entirely for that task and falls
# back to the normal sequential single-agent loop — see supervisor_node()
# in graph.py.
PARALLEL_SAFE_TOOLS: set[str] = {"browser", "files"}

# PyAutoGUI safety
pyautogui.FAILSAFE = True   # move mouse to corner to abort
pyautogui.PAUSE    = 0.4    # small pause after every pyautogui call


# Spotify Web API
SPOTIFY_CLIENT_ID     = os.getenv("SPOTIFY_CLIENT_ID", "")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "")

# Phase 4 — Spotify Web API playback (OAuth Authorization Code flow).
# Must exactly match a Redirect URI registered on the app's Spotify
# Developer Dashboard page, or the authorization exchange will fail.
SPOTIFY_REDIRECT_URI = os.getenv(
    "SPOTIFY_REDIRECT_URI", "http://127.0.0.1:8888/callback"
)
# Scopes needed for read (now-playing) + write (play/pause/transfer)
# access, plus reading the user's own playlist library (needed to find
# personalized/algorithmic playlists like Discover Weekly, which the
# public catalog search generally can't see — see _find_own_playlist).
# Space-separated per Spotify's spec.
SPOTIFY_SCOPES = os.getenv(
    "SPOTIFY_SCOPES",
    "user-read-playback-state user-modify-playback-state "
    "user-read-currently-playing playlist-read-private "
    "playlist-read-collaborative",
)
# Local cache for the OAuth refresh token, so the interactive browser
# consent step only ever needs to happen once. Not committed to git
# (add to .gitignore) — it's equivalent to a password for this app's
# access to the user's Spotify account.
SPOTIFY_TOKEN_CACHE_PATH = str(BASE_DIR / "spotify_token_cache.json")

# Notion API
NOTION_API_KEY = os.getenv("NOTION_API_KEY", "")


# Logging level
LOG_LEVEL = "INFO"   # DEBUG | INFO | WARNING | ERROR

## OLD CODE
# WAIT_SECONDS= 1.5

# SCREENSHOT_WIDTH = 1280

# pyautogui.FAILSAFE = True
# pyautogui.PAUSE = 0.5